build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.13
images:
- dockerfile_path: Dockerfile
  from: src
  to: text-generation-inference
promotion:
  namespace: opendatahub-io
  tag: latest
resources:
  '*':
    limits:
      cpu: "24"
      memory: 32Gi
    requests:
      cpu: "24"
      memory: 32Gi
zz_generated_metadata:
  branch: main
  org: opendatahub-io
  repo: text-generation-inference
